### ISSUE TITLE
Problem resolving crystal shards

### ISSUE THREAD

**Issue by MsBarber** [spider-gazelle/bindata#14]
Since yesterday when a new release there was an incorrect tag set on the latest version of 1.10.0.

This is the error produced when trying to resolve the latest version of this library,

`Fetching https://github.com/spider-gazelle/bindata.git
Failed git ls-tree -r --full-tree --name-only v1.10.0 -- shard.yml (). Maybe a commit, branch or file doesn't exist?`

All releases prior to the current version are formatted as so: 
v1.9.0
v1.9.1
... 

I believe the fix here is to re-release the latest version the 'v' prepended to it.

Please let me know if I can provide any more information to help.

**Comment by stakach** [comment]
sorry and thanks for pointing that out
I've fixed the tag

**Comment by MsBarber** [comment]
Thank you for the hasty reply! Everything is working now.
